from typing import Dict, Any, List
from datetime import datetime
import uuid
from backend.app.orchestrator.streamer import streamer

class SharedMissionMemory:
    """
    In-Memory Shared Mission Store.
    Designed to be easily replaceable with a Supabase database later.
    """
    def __init__(self):
        self.mission: Dict[str, Any] = {}
        self.agent_outputs: Dict[str, Any] = {}
        self.decisions: List[Dict[str, Any]] = []
        self.events: List[Dict[str, Any]] = []

    def createMission(self, mission_data: Dict[str, Any]) -> Dict[str, Any]:
        """Create a new mission and reset state."""
        mission_data["id"] = str(uuid.uuid4())
        mission_data["created_at"] = datetime.utcnow().isoformat()
        
        self.mission = mission_data
        self.agent_outputs = {}
        self.decisions = []
        self.events = []
        return self.mission

    def getMission(self) -> Dict[str, Any]:
        """Retrieve the current mission state."""
        return {
            "mission": self.mission,
            "agent_outputs": self.agent_outputs,
            "decisions": self.decisions,
            "events": self.events
        }

    def updateMission(self, updates: Dict[str, Any]) -> Dict[str, Any]:
        """Update the current mission with new data."""
        self.mission.update(updates)
        self.mission["updated_at"] = datetime.utcnow().isoformat()
        return self.mission

    def saveAgentOutput(self, agent_role: str, output: Any) -> None:
        """Store outputs generated by an agent."""
        self.agent_outputs[agent_role] = output

    def appendDecision(self, decision: Dict[str, Any]) -> None:
        """Append a decision."""
        if "timestamp" not in decision:
            decision["timestamp"] = datetime.utcnow().isoformat()
        self.decisions.append(decision)

    def appendEvent(self, event: Dict[str, Any]) -> None:
        """Append an execution event."""
        if "timestamp" not in event:
            event["timestamp"] = datetime.utcnow().isoformat()
        self.events.append(event)
        
        # Publish to real-time stream
        try:
            streamer.publish(event)
        except Exception:
            pass

# Global singleton memory instance
mission_memory = SharedMissionMemory()
