/* ==========================================================================
   MISSIONOS - REPORT EXPORT SERVICE (Incident Report)
   ========================================================================== */

// Import existing services to gather data
import { incidentService } from '../services/incidentService.js';
import { incidentChecklistService } from '../services/IncidentChecklistService.js';

// jsPDF is loaded globally via CDN (window.jspdf)
const { jsPDF } = window.jspdf || {};

/**
 * Build a plain JS object containing all report sections.
 * This can be used for HTML, CSV, or PDF generation.
 */
function buildReportData(incidentId = null) {
  const incident = incidentService.getActiveIncident(); // currently active incident
  const timeline = incidentService.getTimelineEvents();
  const checklist = incidentChecklistService.getChecklist(incidentId || incident.id);

  // AI Mission Summary – deterministic placeholder
  const aiSummary = `MissionOS identified this as a ${incident.severity.toLowerCase()} severity ${incident.category.toLowerCase()} incident. The response followed the standard escalation workflow, with investigation, mitigation, and verification steps.`;

  // AI Recommendations – deterministic placeholder
  const recommendations = [
    'Improve infrastructure monitoring.',
    'Add automated alerting for early failure detection.',
    'Schedule regular health‑review meetings.',
    'Validate disaster‑recovery procedures.',
    'Review incident escalation thresholds.'
  ];

  // Operational metadata
  const metadata = {
    generatedBy: 'MissionOS',
    userRole: (window.store && window.store.getState && window.store.getState().currentUser?.role) || 'operator',
    exportTimestamp: new Date().toISOString(),
    missionOsVersion: 'v1.0.0'
  };

  return { incident, timeline, checklist, aiSummary, recommendations, metadata };
}

/** Generate HTML report string */
function generateHTMLReport(data) {
  const { incident, timeline, checklist, aiSummary, recommendations, metadata } = data;
  const checklistRows = checklist.map(item => `\n    <tr><td>${item.title}</td><td>${item.completed ? '✓' : '○'}</td></tr>`).join('');
  const timelineRows = timeline.map(ev => `\n    <tr><td>${ev.time}</td><td>${ev.description}</td></tr>`).join('');
  const recList = recommendations.map(r => `<li>${r}</li>`).join('');
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Incident Report – ${incident.id}</title>
  <style>
    body {font-family: system-ui, sans-serif; margin:2rem; color:#1e293b;}
    h1 {font-size:1.6rem; margin-bottom:0.5rem;}
    table {width:100%; border-collapse:collapse; margin-top:0.5rem;}
    th, td {border:1px solid #e2e8f0; padding:0.4rem; text-align:left;}
    th {background:#f1f5f9;}
  </style>
</head>
<body>
  <h1>Incident Report – ${incident.id}</h1>
  <section>
    <h2>Overview</h2>
    <p><strong>Title:</strong> ${incident.title}</p>
    <p><strong>Category:</strong> ${incident.category}</p>
    <p><strong>Severity:</strong> ${incident.severity}</p>
    <p><strong>Status:</strong> ${incident.status}</p>
    <p><strong>Assigned Team:</strong> ${incident.assignedTeam}</p>
    <p><strong>Created:</strong> ${incident.createdAt}</p>
    <p><strong>Resolved:</strong> ${incident.resolvedAt || '—'}</p>
  </section>
  <section>
    <h2>Timeline</h2>
    <table>
      <thead><tr><th>Time</th><th>Event</th></tr></thead>
      <tbody>${timelineRows}</tbody>
    </table>
  </section>
  <section>
    <h2>Action Checklist</h2>
    <table>
      <thead><tr><th>Item</th><th>Status</th></tr></thead>
      <tbody>${checklistRows}</tbody>
    </table>
  </section>
  <section>
    <h2>AI Mission Summary</h2>
    <p>${aiSummary}</p>
  </section>
  <section>
    <h2>Recommended Preventive Actions</h2>
    <ul>${recList}</ul>
  </section>
  <section>
    <h2>Operational Metadata</h2>
    <p><strong>Generated By:</strong> ${metadata.generatedBy}</p>
    <p><strong>User Role:</strong> ${metadata.userRole}</p>
    <p><strong>Export Timestamp:</strong> ${metadata.exportTimestamp}</p>
    <p><strong>MissionOS Version:</strong> ${metadata.missionOsVersion}</p>
  </section>
</body>
</html>`;
}

/** Generate CSV content */
function generateCSVReport(data) {
  const { incident, timeline, checklist, aiSummary, recommendations, metadata } = data;
  const rows = [];
  // Incident overview
  rows.push(['Incident ID', incident.id]);
  rows.push(['Title', incident.title]);
  rows.push(['Category', incident.category]);
  rows.push(['Severity', incident.severity]);
  rows.push(['Status', incident.status]);
  rows.push(['Assigned Team', incident.assignedTeam]);
  rows.push(['Created', incident.createdAt]);
  rows.push(['Resolved', incident.resolvedAt || '']);
  rows.push([]);
  // Timeline
  rows.push(['Timeline']);
  rows.push(['Time', 'Description']);
  timeline.forEach(ev => rows.push([ev.time, ev.description]));
  rows.push([]);
  // Checklist
  rows.push(['Action Checklist']);
  rows.push(['Item', 'Completed']);
  checklist.forEach(it => rows.push([it.title, it.completed ? 'Yes' : 'No']));
  rows.push([]);
  // AI Summary
  rows.push(['AI Mission Summary', aiSummary]);
  rows.push([]);
  // Recommendations
  rows.push(['Recommended Preventive Actions']);
  recommendations.forEach(r => rows.push([r]));
  rows.push([]);
  // Metadata
  rows.push(['Operational Metadata']);
  rows.push(['Generated By', metadata.generatedBy]);
  rows.push(['User Role', metadata.userRole]);
  rows.push(['Export Timestamp', metadata.exportTimestamp]);
  rows.push(['MissionOS Version', metadata.missionOsVersion]);

  // Convert to CSV string with proper escaping
  const csvContent = rows.map(row => row.map(v => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\r\n');
  return csvContent;
}

/** Download helper */
function downloadBlob(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Export as PDF – simple text PDF using jsPDF */
function exportPDF(data) {
  if (!jsPDF) {
    console.error('jsPDF library not loaded');
    return;
  }
  const doc = new jsPDF();
  const lineHeight = 7;
  let y = 10;
  const addLine = txt => { doc.text(txt, 10, y); y += lineHeight; };
  addLine(`Incident Report – ${data.incident.id}`);
  addLine('');
  addLine('Overview:');
  const o = data.incident;
  addLine(`Title: ${o.title}`);
  addLine(`Category: ${o.category}`);
  addLine(`Severity: ${o.severity}`);
  addLine(`Status: ${o.status}`);
  addLine(`Assigned Team: ${o.assignedTeam}`);
  addLine(`Created: ${o.createdAt}`);
  addLine(`Resolved: ${o.resolvedAt || '-'}`);
  addLine('');
  addLine('Timeline:');
  data.timeline.forEach(ev => addLine(`${ev.time} – ${ev.description}`));
  addLine('');
  addLine('Action Checklist:');
  data.checklist.forEach(it => addLine(`${it.title}: ${it.completed ? '✓' : '○'}`));
  addLine('');
  addLine('AI Mission Summary:');
  addLine(data.aiSummary);
  addLine('');
  addLine('Recommended Preventive Actions:');
  data.recommendations.forEach(r => addLine(`- ${r}`));
  addLine('');
  addLine('Operational Metadata:');
  const m = data.metadata;
  addLine(`Generated By: ${m.generatedBy}`);
  addLine(`User Role: ${m.userRole}`);
  addLine(`Export Timestamp: ${m.exportTimestamp}`);
  addLine(`MissionOS Version: ${m.missionOsVersion}`);

  const pdfBlob = doc.output('blob');
  downloadBlob(pdfBlob, `missionos-incident-${data.incident.id}.pdf`, 'application/pdf');
}

export const reportExportService = {
  exportIncidentReport(format = 'pdf') {
    const data = buildReportData();
    switch (format.toLowerCase()) {
      case 'pdf':
        exportPDF(data);
        break;
      case 'html':
        const html = generateHTMLReport(data);
        downloadBlob(html, `missionos-incident-${data.incident.id}.html`, 'text/html');
        break;
      case 'csv':
        const csv = generateCSVReport(data);
        downloadBlob(csv, `missionos-incident-${data.incident.id}.csv`, 'text/csv');
        break;
      default:
        console.warn('Unsupported export format:', format);
    }
  }
};
